### ISSUE TITLE
Option to input "Weight Left For Armor" directly

### ISSUE THREAD

**Issue by PRoosta** [3dots/ds3optimizer#1]
I wanted to suggest that you add back in an option to set the desired amount of weight directly.

The latest update which calculates the weight of other equipment and does the calculation is neat and I am sure that it will be useful to a lot of people.
However, many people (like me) come to the armor optimizer already knowing their build and their weight limit and they want to get a few quick results based on that. Currently they have to look up the weight of every weapon and also input their rings/effects/etc.

It would be much more convenient if both options were available.

**Comment by matta** [comment]
I'd like to add a "me too" comment for this request.

Computing my total equip load from vitality is quite useful. Choosing a max load by fraction instead of by available units is also useful.

But I don't feel like painstakingly selecting all my weapons, shields, rings, etc. is worth the effort. I can easily strip 4 pieces of armor and tell the tool my remaining loadout.  When I do this I'll probably add in a unit or two of fudge factor, because I do like the flexibility of switching out rings and similar weapons without necessarily being forced to re-do my armor.

As far as UI goes, there could be an additional input box for "additional weight" or similar. For those that leave armor/shield/rings unselected, their total would be zero, and all weight would come from this box. For those that want to use the tool, they leave additional weight as zero and select each item in their loadout.

**Comment by Psithief** [comment]
This would also solve the "I must wear crown of dusk" problem.

**Comment by 3dots** [comment]
Yeah I'll code that on Tuesday. Sorry for the wait.

**Comment by 3dots** [comment]
matta, if you want additional weight, just add that into a weapon slot.

For direct input, its done.

**Comment by matta** [comment]
Yes, thank you!
