### ISSUE TITLE
Can we sort the results?

### ISSUE THREAD

**Issue by iancuio** [3dots/ds3optimizer#5]
Is there any possibility to sort the results based on the percentages you give?

Thanks and I respect you hard work!

**Comment by 3dots** [comment]
On a somewhat related note. Have you tried putting in a minimum and then letting the weights decide the further "sorting"? I mean I could add it, but I wanted to ask.

**Comment by iancuio** [comment]
Thanks for the response!

Well, i did not think of that, but it seems rather counter intuitive. The minimum cell is very good, but the thing is, you give the in an unsorted list, and I had averages from 0.270 to 0.290 all over the place. 

Some click listeners on the column headers for toggling A-Z or Z-A (analog to numbers) sorting would be excelent. Optimizer suggests I could get the BEST combination of armor pieces for the given weight.

Anyway, it was just a suggestion, I'll use it anyway, as I have been using it until now. 

Once again, thanks for the hard work.

Praises for you bro! ^^ \o/

**Comment by 3dots** [comment]
Thanks for praises.

The thing is, the driving sorting metric is = PhysicalTotal \* PhysicalWeight + StrikeTotal \* StrikeWeight + .. + MagicTotal \* MagicWeight + FireTotal \* FireWeight + ... + PoiseTota l\* PoiseWeight.

So when you get those numbers 0.270 to 0.290 all over the place from the default weights (giving equal weight to the four physical defense types) it's using the average def. IE if you could sort that intermediate result set by say just Strike, you'd get them nice and sorted, but it might give you the false impression that for that weight those min/maxes on that result set are the only possible values. But that's not true because some of the other physical defenses are bring these particular results on top, whereas there may be results with higher Strike defense but lower other physicals.
